version: '3.8'

services:
  backend:
    image: hackhazard-backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - API_V1_STR=/api/v1
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    networks:
      - inclusive-ai-net

  frontend:
    image: hackhazard-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - inclusive-ai-net

networks:
  inclusive-ai-net:
